// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatTracker;
using StatTracker.DbContexts;

#nullable disable

namespace StatTracker.Migrations
{
    [DbContext(typeof(StatTrackerDbContext))]
    [Migration("20230109021743_AddDecksTable")]
    partial class AddDecksTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StatTracker.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DeckName");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });
#pragma warning restore 612, 618
        }
    }
}
